name: 'VeeTable Action'
description: 'Send data to VeeTable repo'
inputs:
  github-access-token:
    description: 'GitHub personal access token'
    required: true
  action-type:
    description: 'Either "add-version" or "add-test-result"'
    required: true

  ledger-repo-url:
    description: 'URL of repository where ledger.json is/should be stored'
    required: true
  ledger-repo-owner:
    description: 'GitHub username of the ledger repo owner'
    required: true
  ledger-repo-name:
    description: 'GitHub ledger repo name'
    required: true

  version-component-id:
    description: 'Id of the component for which new version is added'
    required: false
  version-tag:
    description: 'Version tag (an arbitrary string, but SemVer is preferred)'
    required: false

  test-setup-id:
    description: 'Id of the setup for which tests were executed'
    required: false
  test-status:
    description: 'Test status'
    required: false
  test-description:
    description: 'Test description'
    required: false
  test-component-version-map:
    description: 'Stringified JSON object that contains key-values for each "componentId":"versionTag". It must be exhaustive'
    required: false
  released-component:
    description: 'Stringified JSON object that contains componentId and tag'
    required: false
  initiator:
    description: 'Stringified JSON object that contains userName of initiator and reason'
    required: false
  link-to-run:
    description: 'Link to tests run in github'
    required: false
  test-params:
    description: 'Autotest params in the setup'
    required: false
runs:
  using: 'node12'
  main: 'build/index.js'
